POST http://localhost:8000/api/v1/register HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
  "name": "Wellington",
  "email": "wellingtonreis@hotmail.com.br",
  "password": "Wr@12345",
  "password_confirmation": "Wr@12345"
}